# Generated by Django 5.2.8 on 2025-11-19 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120)),
                ('svg', models.FileField(upload_to='svg/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='apprentissage.niveau')),
            ],
        ),
    ]
