# Generated by Django 5.2.8 on 2025-11-20 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentissage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='niveaux/'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='ordre',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='niveau',
            name='personnage',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='niveau',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier_svg', models.FileField(upload_to='animations/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprentissage.niveau')),
            ],
        ),
        migrations.DeleteModel(
            name='Activite',
        ),
    ]
