# Generated by Django 5.2.8 on 2025-11-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentissage', '0002_niveau_illustration_niveau_ordre_niveau_personnage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
