# Generated by Django 5.2.8 on 2025-11-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentissage', '0003_alter_animation_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveau',
            name='illustration',
            field=models.FileField(blank=True, null=True, upload_to='niveaux/'),
        ),
    ]
