# Generated by Django 5.2.8 on 2025-11-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentissage', '0004_alter_niveau_illustration'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='nom',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='personnage',
            field=models.CharField(blank=True),
        ),
    ]
