# Generated by Django 5.2.8 on 2025-11-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentissage', '0005_niveau_audio_alter_niveau_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveau',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='niveaux/'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='personnage',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
