# Generated by Django 5.2.8 on 2025-11-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentissage', '0006_alter_niveau_illustration_alter_niveau_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='fichier_svg',
            field=models.ImageField(upload_to='animations_svg/'),
        ),
        migrations.AlterField(
            model_name='animation',
            name='titre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='niveaux_illustrations/'),
        ),
    ]
