# Generated by Django 5.2.8 on 2025-11-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentissage', '0007_alter_animation_fichier_svg_alter_animation_titre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='illustration2',
            field=models.ImageField(blank=True, null=True, upload_to='niveaux_illustrations/'),
        ),
    ]
