# Generated by Django 5.2.8 on 2025-11-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentissage', '0008_niveau_illustration2'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='audio2',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
