# Generated by Django 5.2.8 on 2025-11-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acceuil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('personnage', models.CharField(blank=True, max_length=100)),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='acceuil_illustrations/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/')),
            ],
        ),
        migrations.CreateModel(
            name='niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('personnage', models.CharField(blank=True, max_length=100)),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='niveaux_illustrations/')),
                ('ordre', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
